/**
 * terminal-config command — Write recommended terminal configuration for Claude Code
 *
 * Subcommands:
 *   terminal-config tmux     — Write .tmux.conf optimized for AI coding sessions
 */

import type { Command } from "commander";
import { existsSync, readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { execSync } from "node:child_process";
import { createFormatters } from "../../utils/colors";

// ─── tmux ────────────────────────────────────────────────────────────────────

const TMUX_MARKER = "# oh-my-claude tmux config";

/**
 * Detect the correct clipboard command for the current platform.
 *
 * Priority:
 * - macOS: pbcopy (always available)
 * - Windows/WSL: clip.exe (works from WSL and Git Bash/MSYS2)
 * - Linux: xclip -selection clipboard > xsel --clipboard --input
 */
function detectClipboardCommand(): { copy: string; paste: string; platform: string } {
  if (process.platform === "darwin") {
    return { copy: "pbcopy", paste: "pbpaste", platform: "macOS" };
  }

  if (process.platform === "win32") {
    return { copy: "clip.exe", paste: "powershell.exe -command Get-Clipboard", platform: "Windows" };
  }

  // Linux — check for WSL first
  try {
    const uname = execSync("uname -r", { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
    if (uname.toLowerCase().includes("microsoft") || uname.toLowerCase().includes("wsl")) {
      return { copy: "clip.exe", paste: "powershell.exe -command Get-Clipboard", platform: "WSL" };
    }
  } catch {
    // Not WSL
  }

  // Linux — prefer xclip, fall back to xsel
  try {
    execSync("which xclip", { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
    return { copy: "xclip -selection clipboard", paste: "xclip -selection clipboard -o", platform: "Linux (xclip)" };
  } catch {
    // xclip not found
  }

  try {
    execSync("which xsel", { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
    return { copy: "xsel --clipboard --input", paste: "xsel --clipboard --output", platform: "Linux (xsel)" };
  } catch {
    // xsel not found
  }

  return { copy: "xclip -selection clipboard", paste: "xclip -selection clipboard -o", platform: "Linux (no clipboard tool found)" };
}

function buildTmuxConfig(clipCmd: string): string {
  return `${TMUX_MARKER}
# Generated by: oh-my-claude terminal-config tmux
# Docs: https://github.com/lgcyaxi/oh-my-claude

# ─── Scrollback & History ─────────────────────────────────────────────
# Default is 2000 lines — far too low for AI coding sessions.
set -g history-limit 50000

# ─── Mouse ────────────────────────────────────────────────────────────
# Enable mouse support: scroll = scroll through history (not the dialog),
# click to select pane, drag to resize.
set -g mouse on

# ─── Terminal & Colors ────────────────────────────────────────────────
set -g default-terminal "screen-256color"
# Enable true color (24-bit) if your terminal supports it.
set -ga terminal-overrides ",*256col*:Tc"

# ─── Performance ──────────────────────────────────────────────────────
# Remove escape delay (faster key response, important for vim/neovim).
set -sg escape-time 0
# Increase repeat timeout for prefix key combos.
set -g repeat-time 300

# ─── Window & Pane Settings ──────────────────────────────────────────
# Start windows and panes at 1 (not 0).
set -g base-index 1
setw -g pane-base-index 1
# Renumber windows when one is closed.
set -g renumber-windows on

# ─── Status Bar ───────────────────────────────────────────────────────
set -g status-position bottom
set -g status-interval 5
set -g status-style "bg=#2d2d2d,fg=#cccccc"
set -g status-left "#[fg=#88c0d0,bold] #S "
set -g status-right "#[fg=#888888] %H:%M "
set -g status-left-length 30
set -g status-right-length 30
setw -g window-status-current-style "fg=#88c0d0,bold"
setw -g window-status-style "fg=#888888"

# ─── Copy Mode (vi-style + system clipboard) ─────────────────────────
setw -g mode-keys vi
# Default copy command — all copy operations go to system clipboard (tmux 3.2+).
set -g copy-command "${clipCmd}"
# Enter copy mode with Prefix + [, then use vi keys to navigate.
# Press 'v' to start selection, 'y' to yank (copy to system clipboard).
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "${clipCmd}"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "${clipCmd}"
# Mouse drag selection → system clipboard.
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "${clipCmd}"

# ─── Prefix Key ──────────────────────────────────────────────────────
# Keep default Ctrl-b prefix. Uncomment for Ctrl-a (screen-style):
# set -g prefix C-a
# unbind C-b
# bind C-a send-prefix

# ─── Pane Navigation ─────────────────────────────────────────────────
# Alt+arrow to switch panes without prefix.
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# ─── Reload Config ────────────────────────────────────────────────────
bind r source-file ~/.tmux.conf \\; display-message "Config reloaded"
`;
}

function reloadTmuxConfig(
  ok: ReturnType<typeof createFormatters>["ok"],
  dimText: ReturnType<typeof createFormatters>["dimText"],
): void {
  try {
    execSync("tmux list-sessions", {
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    execSync("tmux source-file ~/.tmux.conf", {
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    console.log();
    console.log(ok("Reloaded tmux config (active sessions updated)"));
  } catch {
    console.log();
    console.log(dimText("Start a new tmux session to apply: tmux new-session"));
  }
}

// ─── Action Implementation ───────────────────────────────────────────────────

function runTmuxAction(options: { show?: boolean; force?: boolean; append?: boolean } = {}) {
  const { c, ok, fail, warn, dimText } = createFormatters();

  // Check tmux availability
  let tmuxVersion = "";
  try {
    tmuxVersion = execSync("tmux -V", {
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    console.log(fail("tmux is not installed."));
    if (process.platform === "win32") {
      console.log(dimText("Install via: winget install psmux"));
    } else if (process.platform === "darwin") {
      console.log(dimText("Install via: brew install tmux"));
    } else {
      console.log(dimText("Install via: sudo apt install tmux"));
    }
    process.exit(1);
  }

  const clipboard = detectClipboardCommand();
  const config = buildTmuxConfig(clipboard.copy);

  console.log(`${c.bold}oh-my-claude terminal-config tmux${c.reset}  (${tmuxVersion})`);
  console.log(dimText(`Clipboard: ${clipboard.copy} (${clipboard.platform})\n`));

  if (options.show) {
    console.log(config);
    return;
  }

  const confPath = join(homedir(), ".tmux.conf");
  const existing = existsSync(confPath);

  if (existing) {
    const content = readFileSync(confPath, "utf-8");

    if (content.includes(TMUX_MARKER)) {
      console.log(warn("oh-my-claude tmux config already present in ~/.tmux.conf"));
      console.log(dimText("Use --force to overwrite, or edit ~/.tmux.conf manually."));
      reloadTmuxConfig(ok, dimText);
      return;
    }

    if (options.append) {
      const separator = "\n\n" + "# ".repeat(35) + "\n";
      writeFileSync(confPath, content + separator + config, "utf-8");
      console.log(ok(`Appended oh-my-claude config to ${confPath}`));
    } else if (options.force) {
      const backupPath = `${confPath}.bak`;
      copyFileSync(confPath, backupPath);
      console.log(dimText(`Backed up existing config to ${backupPath}`));
      writeFileSync(confPath, config, "utf-8");
      console.log(ok(`Wrote ${confPath}`));
    } else {
      console.log(warn(`~/.tmux.conf already exists (${content.split("\n").length} lines)`));
      console.log();
      console.log(`  ${c.cyan}--append${c.reset}  Append oh-my-claude settings to existing config`);
      console.log(`  ${c.cyan}--force${c.reset}   Overwrite (backs up to .tmux.conf.bak)`);
      console.log(`  ${c.cyan}--show${c.reset}    Print the config to stdout (copy what you need)`);
      return;
    }
  } else {
    writeFileSync(confPath, config, "utf-8");
    console.log(ok(`Created ${confPath}`));
  }

  console.log();
  console.log(`${c.bold}Key settings:${c.reset}`);
  console.log(`  history-limit    ${c.cyan}50000${c.reset}     (default: 2000)`);
  console.log(`  mouse            ${c.cyan}on${c.reset}        (scroll = history, not dialog)`);
  console.log(`  escape-time      ${c.cyan}0${c.reset}         (no delay for Esc key)`);
  console.log(`  default-terminal ${c.cyan}screen-256color${c.reset}`);
  console.log(`  mode-keys        ${c.cyan}vi${c.reset}        (vi-style copy mode)`);
  console.log(`  base-index       ${c.cyan}1${c.reset}         (windows start at 1)`);
  console.log(`  clipboard        ${c.cyan}${clipboard.copy}${c.reset} (${clipboard.platform})`);

  if (clipboard.platform.includes("no clipboard tool")) {
    console.log();
    console.log(warn("No clipboard tool found. Install one:"));
    console.log(dimText("  sudo apt install xclip   # Debian/Ubuntu"));
    console.log(dimText("  sudo pacman -S xclip     # Arch"));
    console.log(dimText("  sudo dnf install xclip   # Fedora"));
  }

  reloadTmuxConfig(ok, dimText);
}

// ─── psmux (Windows) ────────────────────────────────────────────────────────

const PSMUX_MARKER = "# oh-my-claude psmux config";

/**
 * Detect the Git Bash path on Windows for psmux's default-shell.
 * Claude Code sends bash-style commands to teammate panes, so
 * the pane shell must be Git Bash (not cmd.exe or PowerShell).
 */
function detectBashPath(): string | null {
  if (process.platform !== "win32") return null;

  // Try common locations
  const candidates = [
    "D:/Applications/Git/usr/bin/bash.exe",
    "C:/Program Files/Git/usr/bin/bash.exe",
    "C:/Program Files (x86)/Git/usr/bin/bash.exe",
  ];

  // Also try to find it via `where` (Git Bash adds itself to PATH)
  try {
    const result = execSync("where bash.exe", {
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (result) {
      // where returns multiple lines, take the first
      const first = result.split("\n")[0]?.trim();
      if (first) candidates.unshift(first.replace(/\\/g, "/"));
    }
  } catch {
    // where not available
  }

  for (const p of candidates) {
    if (existsSync(p)) return p;
  }
  return null;
}

function buildPsmuxConfig(bashPath: string): string {
  return `${PSMUX_MARKER}
# Generated by: oh-my-claude terminal-config psmux
# Docs: https://github.com/lgcyaxi/oh-my-claude
#
# Claude Code team agents send bash-style commands to panes:
#   cd '...' && env VAR=val claude.exe --agent-id ...
# psmux defaults to PowerShell, which can't parse these.
# Setting default-shell to Git Bash (with --login for PATH) fixes this.

set -g default-shell "${bashPath} --login"
`;
}

function runPsmuxAction(options: { show?: boolean; force?: boolean } = {}) {
  const { c, ok, fail, warn, dimText } = createFormatters();

  if (process.platform !== "win32") {
    console.log(dimText("psmux is Windows-only. Use 'oh-my-claude terminal-config tmux' instead."));
    return;
  }

  // Check psmux availability
  let psmuxVersion = "";
  try {
    psmuxVersion = execSync("psmux --version", {
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    console.log(fail("psmux is not installed."));
    console.log(dimText("Install via: winget install psmux"));
    process.exit(1);
  }

  const bashPath = detectBashPath();
  if (!bashPath) {
    console.log(fail("Git Bash not found."));
    console.log(dimText("Install Git for Windows: https://git-scm.com/download/win"));
    process.exit(1);
  }

  const config = buildPsmuxConfig(bashPath);

  console.log(`${c.bold}oh-my-claude terminal-config psmux${c.reset}  (${psmuxVersion})`);
  console.log(dimText(`Bash: ${bashPath}\n`));

  if (options.show) {
    console.log(config);
    return;
  }

  const confPath = join(homedir(), ".psmux.conf");
  const existing = existsSync(confPath);

  if (existing && !options.force) {
    const content = readFileSync(confPath, "utf-8");
    if (content.includes(PSMUX_MARKER)) {
      console.log(ok("oh-my-claude psmux config already present in ~/.psmux.conf"));
      return;
    }
    console.log(warn("~/.psmux.conf already exists."));
    console.log(dimText("Use --force to overwrite."));
    return;
  }

  if (existing) {
    const backupPath = `${confPath}.bak`;
    copyFileSync(confPath, backupPath);
    console.log(dimText(`Backed up existing config to ${backupPath}`));
  }

  writeFileSync(confPath, config, "utf-8");
  console.log(ok(`Created ${confPath}`));
  console.log();
  console.log(`${c.bold}Setting:${c.reset}`);
  console.log(`  default-shell  ${c.cyan}${bashPath} --login${c.reset}`);
  console.log();
  console.log(dimText("Restart psmux sessions for this to take effect."));

  // Apply to running session if possible
  try {
    execSync(`tmux set -g default-shell "${bashPath} --login"`, {
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    console.log(ok("Applied to running psmux session"));
  } catch {
    // No active session
  }
}

// ─── Registration ─────────────────────────────────────────────────────────────

export function registerTerminalConfigCommand(program: Command) {
  const cmd = program
    .command("terminal-config")
    .alias("tc")
    .description("Write terminal configuration for Claude Code sessions")
    .action(() => {
      if (process.platform === "win32") {
        runPsmuxAction();
      } else {
        runTmuxAction();
      }
    });

  // ── tmux subcommand ──────────────────────────────────────────────────────
  cmd
    .command("tmux")
    .description("Write recommended tmux configuration for Claude Code sessions")
    .option("--show", "Show the config without writing")
    .option("--force", "Overwrite existing .tmux.conf without backup")
    .option("--append", "Append to existing .tmux.conf instead of replacing")
    .action((options: { show?: boolean; force?: boolean; append?: boolean }) => {
      runTmuxAction(options);
    });

  // ── psmux subcommand (Windows) ───────────────────────────────────────────
  cmd
    .command("psmux")
    .description("Write psmux configuration for Claude Code team agents on Windows")
    .option("--show", "Show the config without writing")
    .option("--force", "Overwrite existing .psmux.conf")
    .action((options: { show?: boolean; force?: boolean }) => {
      runPsmuxAction(options);
    });
}
