/**
 * terminal-config command — Write recommended terminal configuration for Claude Code
 *
 * Subcommands:
 *   terminal-config tmux     — Write .tmux.conf optimized for AI coding sessions
 *   terminal-config wezterm  — Write .wezterm.lua optimized for AI coding sessions
 */

import type { Command } from "commander";
import { existsSync, readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { execSync } from "node:child_process";
import { createFormatters } from "../../utils/colors";

// ─── tmux ────────────────────────────────────────────────────────────────────

const TMUX_MARKER = "# oh-my-claude tmux config";

/**
 * Detect the correct clipboard command for the current platform.
 *
 * Priority:
 * - macOS: pbcopy (always available)
 * - Windows/WSL: clip.exe (works from WSL and Git Bash/MSYS2)
 * - Linux: xclip -selection clipboard > xsel --clipboard --input
 */
function detectClipboardCommand(): { copy: string; paste: string; platform: string } {
  if (process.platform === "darwin") {
    return { copy: "pbcopy", paste: "pbpaste", platform: "macOS" };
  }

  if (process.platform === "win32") {
    return { copy: "clip.exe", paste: "powershell.exe -command Get-Clipboard", platform: "Windows" };
  }

  // Linux — check for WSL first
  try {
    const uname = execSync("uname -r", { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
    if (uname.toLowerCase().includes("microsoft") || uname.toLowerCase().includes("wsl")) {
      return { copy: "clip.exe", paste: "powershell.exe -command Get-Clipboard", platform: "WSL" };
    }
  } catch {
    // Not WSL
  }

  // Linux — prefer xclip, fall back to xsel
  try {
    execSync("which xclip", { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
    return { copy: "xclip -selection clipboard", paste: "xclip -selection clipboard -o", platform: "Linux (xclip)" };
  } catch {
    // xclip not found
  }

  try {
    execSync("which xsel", { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
    return { copy: "xsel --clipboard --input", paste: "xsel --clipboard --output", platform: "Linux (xsel)" };
  } catch {
    // xsel not found
  }

  return { copy: "xclip -selection clipboard", paste: "xclip -selection clipboard -o", platform: "Linux (no clipboard tool found)" };
}

function buildTmuxConfig(clipCmd: string): string {
  return `${TMUX_MARKER}
# Generated by: oh-my-claude terminal-config tmux
# Docs: https://github.com/lgcyaxi/oh-my-claude

# ─── Scrollback & History ─────────────────────────────────────────────
# Default is 2000 lines — far too low for AI coding sessions.
set -g history-limit 50000

# ─── Mouse ────────────────────────────────────────────────────────────
# Enable mouse support: scroll = scroll through history (not the dialog),
# click to select pane, drag to resize.
set -g mouse on

# ─── Terminal & Colors ────────────────────────────────────────────────
set -g default-terminal "screen-256color"
# Enable true color (24-bit) if your terminal supports it.
set -ga terminal-overrides ",*256col*:Tc"

# ─── Performance ──────────────────────────────────────────────────────
# Remove escape delay (faster key response, important for vim/neovim).
set -sg escape-time 0
# Increase repeat timeout for prefix key combos.
set -g repeat-time 300

# ─── Window & Pane Settings ──────────────────────────────────────────
# Start windows and panes at 1 (not 0).
set -g base-index 1
setw -g pane-base-index 1
# Renumber windows when one is closed.
set -g renumber-windows on

# ─── Status Bar ───────────────────────────────────────────────────────
set -g status-position bottom
set -g status-interval 5
set -g status-style "bg=#2d2d2d,fg=#cccccc"
set -g status-left "#[fg=#88c0d0,bold] #S "
set -g status-right "#[fg=#888888] %H:%M "
set -g status-left-length 30
set -g status-right-length 30
setw -g window-status-current-style "fg=#88c0d0,bold"
setw -g window-status-style "fg=#888888"

# ─── Copy Mode (vi-style + system clipboard) ─────────────────────────
setw -g mode-keys vi
# Default copy command — all copy operations go to system clipboard (tmux 3.2+).
set -g copy-command "${clipCmd}"
# Enter copy mode with Prefix + [, then use vi keys to navigate.
# Press 'v' to start selection, 'y' to yank (copy to system clipboard).
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "${clipCmd}"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "${clipCmd}"
# Mouse drag selection → system clipboard.
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "${clipCmd}"

# ─── Prefix Key ──────────────────────────────────────────────────────
# Keep default Ctrl-b prefix. Uncomment for Ctrl-a (screen-style):
# set -g prefix C-a
# unbind C-b
# bind C-a send-prefix

# ─── Pane Navigation ─────────────────────────────────────────────────
# Alt+arrow to switch panes without prefix.
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# ─── Reload Config ────────────────────────────────────────────────────
bind r source-file ~/.tmux.conf \\; display-message "Config reloaded"
`;
}

function reloadTmuxConfig(
  ok: ReturnType<typeof createFormatters>["ok"],
  dimText: ReturnType<typeof createFormatters>["dimText"],
): void {
  try {
    execSync("tmux list-sessions", {
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    execSync("tmux source-file ~/.tmux.conf", {
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    console.log();
    console.log(ok("Reloaded tmux config (active sessions updated)"));
  } catch {
    console.log();
    console.log(dimText("Start a new tmux session to apply: tmux new-session"));
  }
}

// ─── WezTerm ─────────────────────────────────────────────────────────────────

const WEZTERM_MARKER = "-- oh-my-claude wezterm config";

const WEZTERM_CONFIG = `${WEZTERM_MARKER}
-- Generated by: oh-my-claude terminal-config wezterm
-- Docs: https://github.com/lgcyaxi/oh-my-claude

local wezterm = require 'wezterm'
local act = wezterm.action
local config = wezterm.config_builder()

-- ─── Default Shell (Windows only) ───────────────────────────────────
-- Priority: zsh (if installed in Git Bash) > Git Bash > PowerShell.
if wezterm.target_triple:find('windows') then
  local function file_exists(path)
    local f = io.open(path, 'r')
    if f then f:close(); return true end
    return false
  end

  local function find_git_bash()
    -- Check common install locations
    local candidates = {
      'C:/Program Files/Git/bin/bash.exe',
      'C:/Program Files (x86)/Git/bin/bash.exe',
      (os.getenv('LOCALAPPDATA') or '') .. '/Programs/Git/bin/bash.exe',
      (os.getenv('ProgramFiles') or '') .. '/Git/bin/bash.exe',
      'D:/Program Files/Git/bin/bash.exe',
      'D:/Git/bin/bash.exe',
      'D:/Applications/Git/bin/bash.exe',
    }
    for _, path in ipairs(candidates) do
      if file_exists(path) then return path end
    end
    -- Try 'where git' to find git.exe, then derive bash.exe path.
    -- Read ALL lines (not just first) since git.exe may be in mingw64/bin/ or cmd/.
    local h = io.popen('where git 2>nul')
    if h then
      local output = h:read('*a')
      h:close()
      for git_path in (output or ''):gmatch('[^\\r\\n]+') do
        -- Strategy 1: .../Git/cmd/git.exe → .../Git/bin/bash.exe
        local git_dir = git_path:match('(.+)[/\\\\]cmd[/\\\\]git%.exe$')
        if git_dir then
          local bash = git_dir .. '/bin/bash.exe'
          if file_exists(bash) then return bash end
        end
        -- Strategy 2: .../Git/mingw64/bin/git.exe → .../Git/bin/bash.exe
        local git_root = git_path:match('(.+)[/\\\\]mingw64[/\\\\]bin[/\\\\]git%.exe$')
        if git_root then
          local bash = git_root .. '/bin/bash.exe'
          if file_exists(bash) then return bash end
        end
        -- Strategy 3: .../Git/usr/bin/git.exe → .../Git/bin/bash.exe (MSYS2 layout)
        local usr_root = git_path:match('(.+)[/\\\\]usr[/\\\\]bin[/\\\\]git%.exe$')
        if usr_root then
          local bash = usr_root .. '/bin/bash.exe'
          if file_exists(bash) then return bash end
        end
      end
    end
    return nil
  end

  local bash = find_git_bash()
  if bash then
    -- Check if zsh is available inside Git Bash (e.g., installed via MSYS2/pacman).
    -- If found, launch zsh directly for a better shell experience (plugins, themes).
    -- To install zsh in Git Bash:  https://packages.msys2.org/package/zsh
    -- zsh may be in bin/ or usr/bin/ depending on how Git for Windows was installed.
    local git_bin = bash:match('(.+)/bash%.exe$') or ''
    local git_root = bash:match('(.+)/bin/bash%.exe$') or ''
    local zsh_candidates = {
      git_bin .. '/zsh.exe',           -- same dir as bash (bin/)
      git_root .. '/usr/bin/zsh.exe',  -- MSYS2 layout (usr/bin/)
    }
    local zsh = nil
    for _, zpath in ipairs(zsh_candidates) do
      if file_exists(zpath) then zsh = zpath; break end
    end
    if zsh then
      -- Launch zsh via bash login shell, same as Windows Terminal setup:
      -- bash.exe -i -l -c zsh
      config.default_prog = { bash, '-i', '-l', '-c', 'zsh' }
    else
      config.default_prog = { bash, '--login', '-i' }
    end
  else
    -- Fallback: prefer pwsh.exe (PowerShell Core) > powershell.exe (Windows PowerShell)
    local shell = file_exists('C:/Program Files/PowerShell/7/pwsh.exe') and 'pwsh.exe' or 'powershell.exe'
    config.default_prog = { shell }
  end
end

-- ─── Scrollback & History ─────────────────────────────────────────────
-- Default is 3500 lines — increase for AI coding sessions.
config.scrollback_lines = 50000
config.enable_scroll_bar = true

-- ─── Window & Display ────────────────────────────────────────────────
config.initial_cols = 180
config.initial_rows = 45
config.window_padding = {
  left = 8,
  right = 8,
  top = 4,
  bottom = 4,
}

-- ─── Font ─────────────────────────────────────────────────────────────
-- WezTerm bundles JetBrains Mono and Nerd Fonts by default.
config.font = wezterm.font_with_fallback {
  'JetBrains Mono',
  'Cascadia Code',
  'Noto Color Emoji',
}
config.font_size = 12
config.line_height = 1.1

-- ─── Color Scheme ────────────────────────────────────────────────────
-- WezTerm ships with 700+ schemes. Pick your favorite:
-- 'Dracula', 'One Dark (Gogh)', 'Catppuccin Mocha', 'Nord', 'Gruvbox dark, hard'
config.color_scheme = 'Dracula'

-- Quick select label colors (for URL/path/hash highlighting).
config.colors = {
  quick_select_label_bg = { Color = '#ff6600' },
  quick_select_label_fg = { Color = '#000000' },
  quick_select_match_bg = { Color = '#1e90ff' },
  quick_select_match_fg = { Color = '#ffffff' },
}

-- ─── Tab Bar ──────────────────────────────────────────────────────────
config.enable_tab_bar = true
config.use_fancy_tab_bar = true
config.hide_tab_bar_if_only_one_tab = false
config.tab_bar_at_bottom = false

config.window_frame = {
  font = wezterm.font { family = 'JetBrains Mono', weight = 'Bold' },
  font_size = 11.0,
  active_titlebar_bg = '#222222',
  inactive_titlebar_bg = '#222222',
}

-- ─── Clipboard & Copy ────────────────────────────────────────────────
-- Mouse selection automatically copies to system clipboard (default).
-- No extra config needed — WezTerm always uses system clipboard.
--
-- Copy bindings (built-in, listed for reference):
--   CTRL+SHIFT+C  → Copy to clipboard
--   CTRL+SHIFT+V  → Paste from clipboard
--   SUPER+C/V     → Copy/Paste (macOS)
--   Left-click drag → Select text
--   Release mouse  → Auto-copy to clipboard
--   Alt+drag       → Block/rectangular selection

-- ─── Copy Mode (Vim-style keyboard selection) ────────────────────────
-- CTRL+SHIFT+X to enter copy mode, then:
--   v       → Start selection (character mode)
--   V       → Line selection mode
--   Ctrl+V  → Block selection mode
--   y       → Copy selection and exit
--   /       → Search within scrollback
--   hjkl    → Navigate (Vim-style)
--   w/b/e   → Word navigation
--   0/$     → Line start/end
--   g/G     → Scrollback top/bottom
--   Ctrl+F/B → Page down/up
--   Esc/q   → Exit copy mode

-- ─── Quick Select ────────────────────────────────────────────────────
-- CTRL+SHIFT+SPACE highlights URLs, file paths, git hashes, IPs.
-- Type the label prefix to copy, UPPERCASE to copy+paste.
-- Add custom patterns here:
-- config.quick_select_patterns = {
--   '[A-Z]+-\\\\d+',          -- Jira ticket IDs (e.g., PROJ-123)
--   '[0-9a-f]{7,40}',       -- Git commit hashes
-- }

-- ─── Performance ──────────────────────────────────────────────────────
-- Use WebGpu if available (faster rendering on modern GPUs).
config.front_end = 'WebGpu'
-- Fallback: 'OpenGL'

-- ─── Key Bindings ────────────────────────────────────────────────────
config.keys = {
  -- Search scrollback (regex-capable)
  {
    key = 'f',
    mods = 'CTRL|SHIFT',
    action = act.Search { CaseSensitiveString = '' },
  },

  -- Clear scrollback buffer
  {
    key = 'k',
    mods = 'CTRL|SHIFT',
    action = act.ClearScrollback 'ScrollbackOnly',
  },

  -- Reload configuration
  {
    key = 'r',
    mods = 'CTRL|SHIFT',
    action = act.ReloadConfiguration,
  },

  -- Font size
  {
    key = '-',
    mods = 'CTRL',
    action = act.DecreaseFontSize,
  },
  {
    key = '=',
    mods = 'CTRL',
    action = act.IncreaseFontSize,
  },
  {
    key = '0',
    mods = 'CTRL',
    action = act.ResetFontSize,
  },

  -- Tab management
  {
    key = 't',
    mods = 'CTRL|SHIFT',
    action = act.SpawnTab 'CurrentPaneDomain',
  },
  {
    key = 'w',
    mods = 'CTRL|SHIFT',
    action = act.CloseCurrentTab { confirm = true },
  },

  -- Close current pane (Ctrl+W closes focused pane)
  {
    key = 'w',
    mods = 'CTRL',
    action = act.CloseCurrentPane { confirm = false },
  },

  -- Pane splitting (like tmux)
  {
    key = '|',
    mods = 'CTRL|SHIFT',
    action = act.SplitHorizontal { domain = 'CurrentPaneDomain' },
  },
  {
    key = '_',
    mods = 'CTRL|SHIFT',
    action = act.SplitVertical { domain = 'CurrentPaneDomain' },
  },

  -- Pane navigation (Alt+arrow, same as tmux config)
  {
    key = 'LeftArrow',
    mods = 'ALT',
    action = act.ActivatePaneDirection 'Left',
  },
  {
    key = 'RightArrow',
    mods = 'ALT',
    action = act.ActivatePaneDirection 'Right',
  },
  {
    key = 'UpArrow',
    mods = 'ALT',
    action = act.ActivatePaneDirection 'Up',
  },
  {
    key = 'DownArrow',
    mods = 'ALT',
    action = act.ActivatePaneDirection 'Down',
  },
}

-- ─── Shell Integration ───────────────────────────────────────────────
-- WezTerm supports shell integration for command tracking and
-- "jump to previous prompt" features.
--
-- To enable, add to your shell config:
--
--   Bash/Zsh (~/.bashrc or ~/.zshrc):
--     if [[ -n "$WEZTERM_EXECUTABLE" ]]; then
--       . "$HOME/.config/wezterm/shell-integration.sh" 2>/dev/null
--     fi
--
--   Or download from the WezTerm repo:
--     https://github.com/wez/wezterm/blob/main/assets/shell-integration/wezterm.sh

return config
`;

// ─── Shared action implementations ────────────────────────────────────────────

function runTmuxAction(options: { show?: boolean; force?: boolean; append?: boolean } = {}) {
  const { c, ok, fail, warn, dimText } = createFormatters();

      // Check tmux availability
      let tmuxVersion = "";
      try {
        tmuxVersion = execSync("tmux -V", {
          encoding: "utf-8",
          stdio: ["ignore", "pipe", "ignore"],
        }).trim();
      } catch {
        console.log(fail("tmux is not installed."));
        if (process.platform === "win32") {
          console.log(dimText("Install via: pacman -S tmux (Git Bash/MSYS2)"));
        } else if (process.platform === "darwin") {
          console.log(dimText("Install via: brew install tmux"));
        } else {
          console.log(dimText("Install via: sudo apt install tmux"));
        }
        process.exit(1);
      }

      const clipboard = detectClipboardCommand();
      const config = buildTmuxConfig(clipboard.copy);

      console.log(`${c.bold}oh-my-claude terminal-config tmux${c.reset}  (${tmuxVersion})`);
      console.log(dimText(`Clipboard: ${clipboard.copy} (${clipboard.platform})\n`));

      if (options.show) {
        console.log(config);
        return;
      }

      const confPath = join(homedir(), ".tmux.conf");
      const existing = existsSync(confPath);

      if (existing) {
        const content = readFileSync(confPath, "utf-8");

        if (content.includes(TMUX_MARKER)) {
          console.log(warn("oh-my-claude tmux config already present in ~/.tmux.conf"));
          console.log(dimText("Use --force to overwrite, or edit ~/.tmux.conf manually."));
          reloadTmuxConfig(ok, dimText);
          return;
        }

        if (options.append) {
          const separator = "\n\n" + "# ".repeat(35) + "\n";
          writeFileSync(confPath, content + separator + config, "utf-8");
          console.log(ok(`Appended oh-my-claude config to ${confPath}`));
        } else if (options.force) {
          const backupPath = `${confPath}.bak`;
          copyFileSync(confPath, backupPath);
          console.log(dimText(`Backed up existing config to ${backupPath}`));
          writeFileSync(confPath, config, "utf-8");
          console.log(ok(`Wrote ${confPath}`));
        } else {
          console.log(warn(`~/.tmux.conf already exists (${content.split("\n").length} lines)`));
          console.log();
          console.log(`  ${c.cyan}--append${c.reset}  Append oh-my-claude settings to existing config`);
          console.log(`  ${c.cyan}--force${c.reset}   Overwrite (backs up to .tmux.conf.bak)`);
          console.log(`  ${c.cyan}--show${c.reset}    Print the config to stdout (copy what you need)`);
          return;
        }
      } else {
        writeFileSync(confPath, config, "utf-8");
        console.log(ok(`Created ${confPath}`));
      }

      console.log();
      console.log(`${c.bold}Key settings:${c.reset}`);
      console.log(`  history-limit    ${c.cyan}50000${c.reset}     (default: 2000)`);
      console.log(`  mouse            ${c.cyan}on${c.reset}        (scroll = history, not dialog)`);
      console.log(`  escape-time      ${c.cyan}0${c.reset}         (no delay for Esc key)`);
      console.log(`  default-terminal ${c.cyan}screen-256color${c.reset}`);
      console.log(`  mode-keys        ${c.cyan}vi${c.reset}        (vi-style copy mode)`);
      console.log(`  base-index       ${c.cyan}1${c.reset}         (windows start at 1)`);
      console.log(`  clipboard        ${c.cyan}${clipboard.copy}${c.reset} (${clipboard.platform})`);

      if (clipboard.platform.includes("no clipboard tool")) {
        console.log();
        console.log(warn("No clipboard tool found. Install one:"));
        console.log(dimText("  sudo apt install xclip   # Debian/Ubuntu"));
        console.log(dimText("  sudo pacman -S xclip     # Arch"));
        console.log(dimText("  sudo dnf install xclip   # Fedora"));
      }

  reloadTmuxConfig(ok, dimText);
}

function runWeztermAction(options: { show?: boolean; force?: boolean } = {}) {
  const { c, ok, fail, warn, dimText } = createFormatters();

  // Check WezTerm availability
  let wezVersion = "";
  try {
    wezVersion = execSync("wezterm --version", {
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    console.log(fail("WezTerm is not installed."));
    if (process.platform === "win32") {
      console.log(dimText("Install via: winget install wez.wezterm"));
    } else if (process.platform === "darwin") {
      console.log(dimText("Install via: brew install --cask wezterm"));
    } else {
      console.log(dimText("See: https://wezfurlong.org/wezterm/installation.html"));
    }
    process.exit(1);
  }

  console.log(`${c.bold}oh-my-claude terminal-config wezterm${c.reset}  (${wezVersion})\n`);

  if (options.show) {
    console.log(WEZTERM_CONFIG);
    return;
  }

  const confPath = join(homedir(), ".wezterm.lua");
  const existing = existsSync(confPath);

  if (existing) {
    const content = readFileSync(confPath, "utf-8");

    if (content.includes(WEZTERM_MARKER) && !options.force) {
      console.log(warn("oh-my-claude WezTerm config already present in ~/.wezterm.lua"));
      console.log(dimText("Use --force to overwrite, or edit ~/.wezterm.lua manually."));
      return;
    }

    if (options.force) {
      const backupPath = `${confPath}.bak`;
      copyFileSync(confPath, backupPath);
      console.log(dimText(`Backed up existing config to ${backupPath}`));
      writeFileSync(confPath, WEZTERM_CONFIG, "utf-8");
      console.log(ok(`Wrote ${confPath}`));
    } else {
      console.log(warn(`~/.wezterm.lua already exists (${content.split("\n").length} lines)`));
      console.log();
      console.log(`  ${c.cyan}--force${c.reset}   Overwrite (backs up to .wezterm.lua.bak)`);
      console.log(`  ${c.cyan}--show${c.reset}    Print the config to stdout (copy what you need)`);
      return;
    }
  } else {
    writeFileSync(confPath, WEZTERM_CONFIG, "utf-8");
    console.log(ok(`Created ${confPath}`));
  }

  console.log();
  console.log(`${c.bold}Key settings:${c.reset}`);
  console.log(`  scrollback_lines ${c.cyan}50000${c.reset}     (default: 3500)`);
  console.log(`  font             ${c.cyan}JetBrains Mono${c.reset}`);
  console.log(`  color_scheme     ${c.cyan}Dracula${c.reset}`);
  console.log(`  front_end        ${c.cyan}WebGpu${c.reset}    (faster rendering)`);
  console.log(`  clipboard        ${c.cyan}auto${c.reset}      (copy on select, system clipboard)`);
  console.log(`  copy_mode        ${c.cyan}Ctrl+Shift+X${c.reset} (Vim-style selection)`);
  console.log(`  quick_select     ${c.cyan}Ctrl+Shift+Space${c.reset} (URL/path/hash picker)`);
  console.log(`  search           ${c.cyan}Ctrl+Shift+F${c.reset} (regex scrollback search)`);
  console.log(`  default_shell    ${c.cyan}auto${c.reset}      (zsh > Git Bash > PowerShell)`);

  console.log();
  console.log(`${c.bold}Key features (built-in, no plugins needed):${c.reset}`);
  console.log(`  ${c.cyan}Copy mode${c.reset}      Vim-style keyboard text selection`);
  console.log(`  ${c.cyan}Quick select${c.reset}   Highlight & copy URLs, paths, hashes`);
  console.log(`  ${c.cyan}Search${c.reset}         Regex search through scrollback`);
  console.log(`  ${c.cyan}Pane split${c.reset}     Ctrl+Shift+| (horizontal), Ctrl+Shift+_ (vertical)`);
  console.log(`  ${c.cyan}Alt+arrow${c.reset}      Navigate panes (same as tmux config)`);

  if (process.platform === "win32") {
    console.log();
    console.log(`${c.bold}Zsh on Windows (optional):${c.reset}`);
    console.log(dimText("  If zsh is found in your Git Bash installation, WezTerm will use it automatically."));
    console.log(dimText("  To install zsh in Git Bash (MSYS2):"));
    console.log(dimText("    1. Download zsh package from https://packages.msys2.org/package/zsh"));
    console.log(dimText("    2. Extract to your Git installation directory (e.g., D:/Applications/Git/)"));
    console.log(dimText("    3. Restart WezTerm — zsh will be detected and used as default shell"));
  }

  console.log();
  console.log(dimText("Shell integration (optional — command tracking, jump to prompt):"));
  console.log(dimText('  Add to ~/.bashrc or ~/.zshrc:'));
  console.log(dimText('    if [[ -n "$WEZTERM_EXECUTABLE" ]]; then'));
  console.log(dimText('      . "$HOME/.config/wezterm/shell-integration.sh" 2>/dev/null'));
  console.log(dimText('    fi'));
  console.log(dimText("  See: https://wezfurlong.org/wezterm/shell-integration.html"));
}

// ─── Registration ─────────────────────────────────────────────────────────────

export function registerTerminalConfigCommand(program: Command) {
  const cmd = program
    .command("terminal-config")
    .alias("tc")
    .description("Write terminal configuration for Claude Code sessions")
    .action(async () => {
      const { c, dimText } = createFormatters();
      const { select } = await import("@inquirer/prompts");

      console.log(`${c.bold}Terminal Configuration${c.reset}\n`);

      const choice = await select({
        message: "Select terminal to configure:",
        choices: [
          { name: "tmux      — Write ~/.tmux.conf (optimized for AI coding sessions)", value: "tmux" },
          { name: "wezterm   — Write ~/.wezterm.lua (optimized for AI coding sessions)", value: "wezterm" },
          { name: "Cancel", value: "cancel" },
        ],
      });

      if (choice === "cancel") {
        console.log(dimText("Cancelled."));
        return;
      }

      if (choice === "tmux") {
        runTmuxAction();
      } else {
        runWeztermAction();
      }
    });

  // ── tmux subcommand ──────────────────────────────────────────────────────
  cmd
    .command("tmux")
    .description("Write recommended tmux configuration for Claude Code sessions")
    .option("--show", "Show the config without writing")
    .option("--force", "Overwrite existing .tmux.conf without backup")
    .option("--append", "Append to existing .tmux.conf instead of replacing")
    .action((options: { show?: boolean; force?: boolean; append?: boolean }) => {
      runTmuxAction(options);
    });

  // ── wezterm subcommand ───────────────────────────────────────────────────
  cmd
    .command("wezterm")
    .description("Write recommended WezTerm configuration for Claude Code sessions")
    .option("--show", "Show the config without writing")
    .option("--force", "Overwrite existing .wezterm.lua without backup")
    .action((options: { show?: boolean; force?: boolean }) => {
      runWeztermAction(options);
    });
}
