/**
 * tmux-config command — Write recommended tmux configuration for Claude Code
 *
 * Writes a .tmux.conf with settings optimized for `oh-my-claude cc` tmux sessions:
 * - Large scrollback buffer (50,000 lines)
 * - Mouse mode enabled (scroll = history, not dialog)
 * - 256-color terminal
 * - No escape delay
 * - Vi-style copy mode with system clipboard integration
 * - Cross-platform clipboard: pbcopy (macOS), clip.exe (Windows/WSL), xclip (Linux)
 */

import type { Command } from "commander";
import { existsSync, readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { execSync } from "node:child_process";
import { createFormatters } from "../utils/colors";

const OMC_MARKER = "# oh-my-claude tmux config";

/**
 * Detect the correct clipboard command for the current platform.
 *
 * Priority:
 * - macOS: pbcopy (always available)
 * - Windows/WSL: clip.exe (works from WSL and Git Bash/MSYS2)
 * - Linux: xclip -selection clipboard > xsel --clipboard --input
 */
function detectClipboardCommand(): { copy: string; paste: string; platform: string } {
  // macOS
  if (process.platform === "darwin") {
    return { copy: "pbcopy", paste: "pbpaste", platform: "macOS" };
  }

  // Windows native (Git Bash / MSYS2)
  if (process.platform === "win32") {
    return { copy: "clip.exe", paste: "powershell.exe -command Get-Clipboard", platform: "Windows" };
  }

  // Linux — check for WSL first
  try {
    const uname = execSync("uname -r", { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
    if (uname.toLowerCase().includes("microsoft") || uname.toLowerCase().includes("wsl")) {
      return { copy: "clip.exe", paste: "powershell.exe -command Get-Clipboard", platform: "WSL" };
    }
  } catch {
    // Not WSL
  }

  // Linux — prefer xclip, fall back to xsel
  try {
    execSync("which xclip", { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
    return { copy: "xclip -selection clipboard", paste: "xclip -selection clipboard -o", platform: "Linux (xclip)" };
  } catch {
    // xclip not found
  }

  try {
    execSync("which xsel", { encoding: "utf-8", stdio: ["ignore", "pipe", "ignore"] });
    return { copy: "xsel --clipboard --input", paste: "xsel --clipboard --output", platform: "Linux (xsel)" };
  } catch {
    // xsel not found
  }

  // Fallback — use xclip and warn
  return { copy: "xclip -selection clipboard", paste: "xclip -selection clipboard -o", platform: "Linux (no clipboard tool found)" };
}

function buildTmuxConfig(clipCmd: string): string {
  return `${OMC_MARKER}
# Generated by: oh-my-claude tmux-config
# Docs: https://github.com/lgcyaxi/oh-my-claude

# ─── Scrollback & History ─────────────────────────────────────────────
# Default is 2000 lines — far too low for AI coding sessions.
set -g history-limit 50000

# ─── Mouse ────────────────────────────────────────────────────────────
# Enable mouse support: scroll = scroll through history (not the dialog),
# click to select pane, drag to resize.
set -g mouse on

# ─── Terminal & Colors ────────────────────────────────────────────────
set -g default-terminal "screen-256color"
# Enable true color (24-bit) if your terminal supports it.
set -ga terminal-overrides ",*256col*:Tc"

# ─── Performance ──────────────────────────────────────────────────────
# Remove escape delay (faster key response, important for vim/neovim).
set -sg escape-time 0
# Increase repeat timeout for prefix key combos.
set -g repeat-time 300

# ─── Window & Pane Settings ──────────────────────────────────────────
# Start windows and panes at 1 (not 0).
set -g base-index 1
setw -g pane-base-index 1
# Renumber windows when one is closed.
set -g renumber-windows on

# ─── Status Bar ───────────────────────────────────────────────────────
set -g status-position bottom
set -g status-interval 5
set -g status-style "bg=#2d2d2d,fg=#cccccc"
set -g status-left "#[fg=#88c0d0,bold] #S "
set -g status-right "#[fg=#888888] %H:%M "
set -g status-left-length 30
set -g status-right-length 30
setw -g window-status-current-style "fg=#88c0d0,bold"
setw -g window-status-style "fg=#888888"

# ─── Copy Mode (vi-style + system clipboard) ─────────────────────────
setw -g mode-keys vi
# Default copy command — all copy operations go to system clipboard (tmux 3.2+).
set -g copy-command "${clipCmd}"
# Enter copy mode with Prefix + [, then use vi keys to navigate.
# Press 'v' to start selection, 'y' to yank (copy to system clipboard).
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "${clipCmd}"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "${clipCmd}"
# Mouse drag selection → system clipboard.
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "${clipCmd}"

# ─── Prefix Key ──────────────────────────────────────────────────────
# Keep default Ctrl-b prefix. Uncomment for Ctrl-a (screen-style):
# set -g prefix C-a
# unbind C-b
# bind C-a send-prefix

# ─── Pane Navigation ─────────────────────────────────────────────────
# Alt+arrow to switch panes without prefix.
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# ─── Reload Config ────────────────────────────────────────────────────
bind r source-file ~/.tmux.conf \\; display-message "Config reloaded"
`;
}

export function registerTmuxConfigCommand(program: Command) {
  program
    .command("tmux-config")
    .description("Write recommended tmux configuration for Claude Code sessions")
    .option("--show", "Show the config without writing")
    .option("--force", "Overwrite existing .tmux.conf without backup")
    .option("--append", "Append to existing .tmux.conf instead of replacing")
    .action((options: { show?: boolean; force?: boolean; append?: boolean }) => {
      const { c, ok, fail, warn, dimText } = createFormatters();

      // Check tmux availability
      let tmuxVersion = "";
      try {
        tmuxVersion = execSync("tmux -V", {
          encoding: "utf-8",
          stdio: ["ignore", "pipe", "ignore"],
        }).trim();
      } catch {
        console.log(fail("tmux is not installed."));
        if (process.platform === "win32") {
          console.log(dimText("Install via: pacman -S tmux (Git Bash/MSYS2)"));
        } else if (process.platform === "darwin") {
          console.log(dimText("Install via: brew install tmux"));
        } else {
          console.log(dimText("Install via: sudo apt install tmux"));
        }
        process.exit(1);
      }

      // Detect clipboard command for this platform
      const clipboard = detectClipboardCommand();
      const config = buildTmuxConfig(clipboard.copy);

      console.log(`${c.bold}oh-my-claude tmux-config${c.reset}  (${tmuxVersion})`);
      console.log(dimText(`Clipboard: ${clipboard.copy} (${clipboard.platform})\n`));

      // Show mode
      if (options.show) {
        console.log(config);
        return;
      }

      const confPath = join(homedir(), ".tmux.conf");
      const existing = existsSync(confPath);

      if (existing) {
        const content = readFileSync(confPath, "utf-8");

        // Check if we already wrote this
        if (content.includes(OMC_MARKER)) {
          console.log(warn("oh-my-claude tmux config already present in ~/.tmux.conf"));
          console.log(dimText("Use --force to overwrite, or edit ~/.tmux.conf manually."));

          // Still reload if tmux server is running
          reloadTmuxConfig(ok, dimText);
          return;
        }

        if (options.append) {
          // Append our config to the end
          const separator = "\n\n" + "# ".repeat(35) + "\n";
          writeFileSync(confPath, content + separator + config, "utf-8");
          console.log(ok(`Appended oh-my-claude config to ${confPath}`));
        } else if (options.force) {
          // Backup and overwrite
          const backupPath = `${confPath}.bak`;
          copyFileSync(confPath, backupPath);
          console.log(dimText(`Backed up existing config to ${backupPath}`));
          writeFileSync(confPath, config, "utf-8");
          console.log(ok(`Wrote ${confPath}`));
        } else {
          // Warn and ask
          console.log(warn(`~/.tmux.conf already exists (${content.split("\n").length} lines)`));
          console.log();
          console.log(`  ${c.cyan}--append${c.reset}  Append oh-my-claude settings to existing config`);
          console.log(`  ${c.cyan}--force${c.reset}   Overwrite (backs up to .tmux.conf.bak)`);
          console.log(`  ${c.cyan}--show${c.reset}    Print the config to stdout (copy what you need)`);
          return;
        }
      } else {
        // No existing config — write fresh
        writeFileSync(confPath, config, "utf-8");
        console.log(ok(`Created ${confPath}`));
      }

      // Summary of key settings
      console.log();
      console.log(`${c.bold}Key settings:${c.reset}`);
      console.log(`  history-limit    ${c.cyan}50000${c.reset}     (default: 2000)`);
      console.log(`  mouse            ${c.cyan}on${c.reset}        (scroll = history, not dialog)`);
      console.log(`  escape-time      ${c.cyan}0${c.reset}         (no delay for Esc key)`);
      console.log(`  default-terminal ${c.cyan}screen-256color${c.reset}`);
      console.log(`  mode-keys        ${c.cyan}vi${c.reset}        (vi-style copy mode)`);
      console.log(`  base-index       ${c.cyan}1${c.reset}         (windows start at 1)`);
      console.log(`  clipboard        ${c.cyan}${clipboard.copy}${c.reset} (${clipboard.platform})`);

      // Warn if no clipboard tool on Linux
      if (clipboard.platform.includes("no clipboard tool")) {
        console.log();
        console.log(warn("No clipboard tool found. Install one:"));
        console.log(dimText("  sudo apt install xclip   # Debian/Ubuntu"));
        console.log(dimText("  sudo pacman -S xclip     # Arch"));
        console.log(dimText("  sudo dnf install xclip   # Fedora"));
      }

      // Reload if tmux is running
      reloadTmuxConfig(ok, dimText);
    });
}

function reloadTmuxConfig(
  ok: ReturnType<typeof createFormatters>["ok"],
  dimText: ReturnType<typeof createFormatters>["dimText"],
): void {
  try {
    // Check if tmux server is running
    execSync("tmux list-sessions", {
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    });

    // Server is running — reload
    execSync("tmux source-file ~/.tmux.conf", {
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    console.log();
    console.log(ok("Reloaded tmux config (active sessions updated)"));
  } catch {
    console.log();
    console.log(dimText("Start a new tmux session to apply: tmux new-session"));
  }
}
