/**
 * wezterm-config command — Write recommended WezTerm configuration for Claude Code
 *
 * Writes a .wezterm.lua with settings optimized for AI coding sessions:
 * - Large scrollback buffer (10,000 lines)
 * - System clipboard integration (copy on select)
 * - Vi-style copy mode + quick select
 * - Shell integration hints
 * - Font and color scheme defaults
 * - Tab bar and window configuration
 */

import type { Command } from "commander";
import { existsSync, readFileSync, writeFileSync, copyFileSync } from "node:fs";
import { join } from "node:path";
import { homedir } from "node:os";
import { execSync } from "node:child_process";
import { createFormatters } from "../utils/colors";

const OMC_MARKER = "-- oh-my-claude wezterm config";

const WEZTERM_CONFIG = `${OMC_MARKER}
-- Generated by: oh-my-claude wezterm-config
-- Docs: https://github.com/lgcyaxi/oh-my-claude

local wezterm = require 'wezterm'
local act = wezterm.action
local config = wezterm.config_builder()

-- ─── Default Shell (Windows only) ───────────────────────────────────
-- Priority: zsh (if installed in Git Bash) > Git Bash > PowerShell.
if wezterm.target_triple:find('windows') then
  local function find_git_bash()
    -- Check common install locations
    local candidates = {
      'C:/Program Files/Git/bin/bash.exe',
      'C:/Program Files (x86)/Git/bin/bash.exe',
      (os.getenv('LOCALAPPDATA') or '') .. '/Programs/Git/bin/bash.exe',
      (os.getenv('ProgramFiles') or '') .. '/Git/bin/bash.exe',
      'D:/Program Files/Git/bin/bash.exe',
      'D:/Git/bin/bash.exe',
    }
    for _, path in ipairs(candidates) do
      local f = io.open(path, 'r')
      if f then f:close(); return path end
    end
    -- Try 'where git' to find git.exe, then derive bash.exe path
    local h = io.popen('where git 2>nul')
    if h then
      local git_path = h:read('*l')
      h:close()
      if git_path then
        -- git.exe is typically at .../Git/cmd/git.exe → bash is at .../Git/bin/bash.exe
        local git_dir = git_path:match('(.+)[/\\\\]cmd[/\\\\]git%.exe$')
        if git_dir then
          local bash = git_dir .. '/bin/bash.exe'
          local f = io.open(bash, 'r')
          if f then f:close(); return bash end
        end
      end
    end
    return nil
  end

  local bash = find_git_bash()
  if bash then
    -- Check if zsh is available inside Git Bash (e.g., installed via MSYS2/pacman).
    -- If found, launch zsh directly for a better shell experience (plugins, themes).
    -- To install zsh in Git Bash:  https://packages.msys2.org/package/zsh
    -- zsh may be in bin/ or usr/bin/ depending on how Git for Windows was installed.
    local git_bin = bash:match('(.+)/bash%.exe$') or ''
    local git_root = bash:match('(.+)/bin/bash%.exe$') or ''
    local zsh_candidates = {
      git_bin .. '/zsh.exe',           -- same dir as bash (bin/)
      git_root .. '/usr/bin/zsh.exe',  -- MSYS2 layout (usr/bin/)
    }
    local zsh = nil
    for _, zpath in ipairs(zsh_candidates) do
      local zf = io.open(zpath, 'r')
      if zf then zf:close(); zsh = zpath; break end
    end
    if zsh then
      -- Launch zsh via bash login shell, same as Windows Terminal setup:
      -- bash.exe -i -l -c zsh
      config.default_prog = { bash, '-i', '-l', '-c', 'zsh' }
    else
      config.default_prog = { bash, '--login', '-i' }
    end
  else
    config.default_prog = { 'pwsh.exe' }
  end
end

-- ─── Scrollback & History ─────────────────────────────────────────────
-- Default is 3500 lines — increase for AI coding sessions.
config.scrollback_lines = 50000
config.enable_scroll_bar = true

-- ─── Window & Display ────────────────────────────────────────────────
config.initial_cols = 180
config.initial_rows = 45
config.window_padding = {
  left = 8,
  right = 8,
  top = 4,
  bottom = 4,
}

-- ─── Font ─────────────────────────────────────────────────────────────
-- WezTerm bundles JetBrains Mono and Nerd Fonts by default.
config.font = wezterm.font_with_fallback {
  'JetBrains Mono',
  'Cascadia Code',
  'Noto Color Emoji',
}
config.font_size = 12
config.line_height = 1.1

-- ─── Color Scheme ────────────────────────────────────────────────────
-- WezTerm ships with 700+ schemes. Pick your favorite:
-- 'Dracula', 'One Dark (Gogh)', 'Catppuccin Mocha', 'Nord', 'Gruvbox dark, hard'
config.color_scheme = 'Dracula'

-- Quick select label colors (for URL/path/hash highlighting).
config.colors = {
  quick_select_label_bg = { Color = '#ff6600' },
  quick_select_label_fg = { Color = '#000000' },
  quick_select_match_bg = { Color = '#1e90ff' },
  quick_select_match_fg = { Color = '#ffffff' },
}

-- ─── Tab Bar ──────────────────────────────────────────────────────────
config.enable_tab_bar = true
config.use_fancy_tab_bar = true
config.hide_tab_bar_if_only_one_tab = false
config.tab_bar_at_bottom = false

config.window_frame = {
  font = wezterm.font { family = 'JetBrains Mono', weight = 'Bold' },
  font_size = 11.0,
  active_titlebar_bg = '#222222',
  inactive_titlebar_bg = '#222222',
}

-- ─── Clipboard & Copy ────────────────────────────────────────────────
-- Mouse selection automatically copies to system clipboard (default).
-- No extra config needed — WezTerm always uses system clipboard.
--
-- Copy bindings (built-in, listed for reference):
--   CTRL+SHIFT+C  → Copy to clipboard
--   CTRL+SHIFT+V  → Paste from clipboard
--   SUPER+C/V     → Copy/Paste (macOS)
--   Left-click drag → Select text
--   Release mouse  → Auto-copy to clipboard
--   Alt+drag       → Block/rectangular selection

-- ─── Copy Mode (Vim-style keyboard selection) ────────────────────────
-- CTRL+SHIFT+X to enter copy mode, then:
--   v       → Start selection (character mode)
--   V       → Line selection mode
--   Ctrl+V  → Block selection mode
--   y       → Copy selection and exit
--   /       → Search within scrollback
--   hjkl    → Navigate (Vim-style)
--   w/b/e   → Word navigation
--   0/$     → Line start/end
--   g/G     → Scrollback top/bottom
--   Ctrl+F/B → Page down/up
--   Esc/q   → Exit copy mode

-- ─── Quick Select ────────────────────────────────────────────────────
-- CTRL+SHIFT+SPACE highlights URLs, file paths, git hashes, IPs.
-- Type the label prefix to copy, UPPERCASE to copy+paste.
-- Add custom patterns here:
-- config.quick_select_patterns = {
--   '[A-Z]+-\\d+',          -- Jira ticket IDs (e.g., PROJ-123)
--   '[0-9a-f]{7,40}',       -- Git commit hashes
-- }

-- ─── Performance ──────────────────────────────────────────────────────
-- Use WebGpu if available (faster rendering on modern GPUs).
config.front_end = 'WebGpu'
-- Fallback: 'OpenGL'

-- ─── Key Bindings ────────────────────────────────────────────────────
config.keys = {
  -- Search scrollback (regex-capable)
  {
    key = 'f',
    mods = 'CTRL|SHIFT',
    action = act.Search { CaseSensitiveString = '' },
  },

  -- Clear scrollback buffer
  {
    key = 'k',
    mods = 'CTRL|SHIFT',
    action = act.ClearScrollback 'ScrollbackOnly',
  },

  -- Reload configuration
  {
    key = 'r',
    mods = 'CTRL|SHIFT',
    action = act.ReloadConfiguration,
  },

  -- Font size
  {
    key = '-',
    mods = 'CTRL',
    action = act.DecreaseFontSize,
  },
  {
    key = '=',
    mods = 'CTRL',
    action = act.IncreaseFontSize,
  },
  {
    key = '0',
    mods = 'CTRL',
    action = act.ResetFontSize,
  },

  -- Tab management
  {
    key = 't',
    mods = 'CTRL|SHIFT',
    action = act.SpawnTab 'CurrentPaneDomain',
  },
  {
    key = 'w',
    mods = 'CTRL|SHIFT',
    action = act.CloseCurrentTab { confirm = true },
  },

  -- Pane splitting (like tmux)
  {
    key = '|',
    mods = 'CTRL|SHIFT',
    action = act.SplitHorizontal { domain = 'CurrentPaneDomain' },
  },
  {
    key = '_',
    mods = 'CTRL|SHIFT',
    action = act.SplitVertical { domain = 'CurrentPaneDomain' },
  },

  -- Pane navigation (Alt+arrow, like our tmux config)
  {
    key = 'LeftArrow',
    mods = 'ALT',
    action = act.ActivatePaneDirection 'Left',
  },
  {
    key = 'RightArrow',
    mods = 'ALT',
    action = act.ActivatePaneDirection 'Right',
  },
  {
    key = 'UpArrow',
    mods = 'ALT',
    action = act.ActivatePaneDirection 'Up',
  },
  {
    key = 'DownArrow',
    mods = 'ALT',
    action = act.ActivatePaneDirection 'Down',
  },
}

-- ─── Shell Integration ───────────────────────────────────────────────
-- WezTerm supports shell integration for command tracking and
-- "jump to previous prompt" features.
--
-- To enable, add to your shell config:
--
--   Bash/Zsh (~/.bashrc or ~/.zshrc):
--     if [[ -n "$WEZTERM_EXECUTABLE" ]]; then
--       . "$HOME/.config/wezterm/shell-integration.sh" 2>/dev/null
--     fi
--
--   Or download from the WezTerm repo:
--     https://github.com/wez/wezterm/blob/main/assets/shell-integration/wezterm.sh

return config
`;

export function registerWezTermConfigCommand(program: Command) {
  program
    .command("wezterm-config")
    .description("Write recommended WezTerm configuration for Claude Code sessions")
    .option("--show", "Show the config without writing")
    .option("--force", "Overwrite existing .wezterm.lua without backup")
    .action((options: { show?: boolean; force?: boolean }) => {
      const { c, ok, fail, warn, dimText } = createFormatters();

      // Check WezTerm availability
      let wezVersion = "";
      try {
        wezVersion = execSync("wezterm --version", {
          encoding: "utf-8",
          stdio: ["ignore", "pipe", "ignore"],
        }).trim();
      } catch {
        console.log(fail("WezTerm is not installed."));
        if (process.platform === "win32") {
          console.log(dimText("Install via: winget install wez.wezterm"));
        } else if (process.platform === "darwin") {
          console.log(dimText("Install via: brew install --cask wezterm"));
        } else {
          console.log(dimText("See: https://wezfurlong.org/wezterm/installation.html"));
        }
        process.exit(1);
      }

      console.log(`${c.bold}oh-my-claude wezterm-config${c.reset}  (${wezVersion})\n`);

      // Show mode
      if (options.show) {
        console.log(WEZTERM_CONFIG);
        return;
      }

      // WezTerm config path: ~/.wezterm.lua (simplest, works everywhere)
      const confPath = join(homedir(), ".wezterm.lua");
      const existing = existsSync(confPath);

      if (existing) {
        const content = readFileSync(confPath, "utf-8");

        // Check if we already wrote this
        if (content.includes(OMC_MARKER) && !options.force) {
          console.log(warn("oh-my-claude WezTerm config already present in ~/.wezterm.lua"));
          console.log(dimText("Use --force to overwrite, or edit ~/.wezterm.lua manually."));
          return;
        }

        if (options.force) {
          // Backup and overwrite
          const backupPath = `${confPath}.bak`;
          copyFileSync(confPath, backupPath);
          console.log(dimText(`Backed up existing config to ${backupPath}`));
          writeFileSync(confPath, WEZTERM_CONFIG, "utf-8");
          console.log(ok(`Wrote ${confPath}`));
        } else {
          // Warn and ask
          console.log(warn(`~/.wezterm.lua already exists (${content.split("\n").length} lines)`));
          console.log();
          console.log(`  ${c.cyan}--force${c.reset}   Overwrite (backs up to .wezterm.lua.bak)`);
          console.log(`  ${c.cyan}--show${c.reset}    Print the config to stdout (copy what you need)`);
          return;
        }
      } else {
        // No existing config — write fresh
        writeFileSync(confPath, WEZTERM_CONFIG, "utf-8");
        console.log(ok(`Created ${confPath}`));
      }

      // Summary of key settings
      console.log();
      console.log(`${c.bold}Key settings:${c.reset}`);
      console.log(`  scrollback_lines ${c.cyan}50000${c.reset}     (default: 3500)`);
      console.log(`  font             ${c.cyan}JetBrains Mono${c.reset}`);
      console.log(`  color_scheme     ${c.cyan}Dracula${c.reset}`);
      console.log(`  front_end        ${c.cyan}WebGpu${c.reset}    (faster rendering)`);
      console.log(`  clipboard        ${c.cyan}auto${c.reset}      (copy on select, system clipboard)`);
      console.log(`  copy_mode        ${c.cyan}Ctrl+Shift+X${c.reset} (Vim-style selection)`);
      console.log(`  quick_select     ${c.cyan}Ctrl+Shift+Space${c.reset} (URL/path/hash picker)`);
      console.log(`  search           ${c.cyan}Ctrl+Shift+F${c.reset} (regex scrollback search)`);
      console.log(`  default_shell    ${c.cyan}auto${c.reset}      (zsh > Git Bash > PowerShell)`);

      // Feature highlights
      console.log();
      console.log(`${c.bold}Key features (built-in, no plugins needed):${c.reset}`);
      console.log(`  ${c.cyan}Copy mode${c.reset}      Vim-style keyboard text selection`);
      console.log(`  ${c.cyan}Quick select${c.reset}   Highlight & copy URLs, paths, hashes`);
      console.log(`  ${c.cyan}Search${c.reset}         Regex search through scrollback`);
      console.log(`  ${c.cyan}Pane split${c.reset}     Ctrl+Shift+| (horizontal), Ctrl+Shift+_ (vertical)`);
      console.log(`  ${c.cyan}Alt+arrow${c.reset}      Navigate panes (same as tmux config)`);

      // Zsh tip (Windows only)
      if (process.platform === "win32") {
        console.log();
        console.log(`${c.bold}Zsh on Windows (optional):${c.reset}`);
        console.log(dimText("  If zsh is found in your Git Bash installation, WezTerm will use it automatically."));
        console.log(dimText("  To install zsh in Git Bash (MSYS2):"));
        console.log(dimText("    1. Download zsh package from https://packages.msys2.org/package/zsh"));
        console.log(dimText("    2. Extract to your Git installation directory (e.g., D:/Applications/Git/)"));
        console.log(dimText("    3. Restart WezTerm — zsh will be detected and used as default shell"));
      }

      // Shell integration hint
      console.log();
      console.log(dimText("Shell integration (optional — command tracking, jump to prompt):"));
      console.log(dimText('  Add to ~/.bashrc or ~/.zshrc:'));
      console.log(dimText('    if [[ -n "$WEZTERM_EXECUTABLE" ]]; then'));
      console.log(dimText('      . "$HOME/.config/wezterm/shell-integration.sh" 2>/dev/null'));
      console.log(dimText('    fi'));
      console.log(dimText("  See: https://wezfurlong.org/wezterm/shell-integration.html"));
    });
}
